### HOMEPAGE

title: Website

#-----------------------------------------------------------------------------------

# 1. MATOMO

#-----------------------------------------------------------------------------------

tabs:
  #-- 1. MATOMO

  matomo:
    label: Analytics
    icon: preview
    columns:
      - width: 3/4
        sections:
          main:
            type: matomo-main
      - width: 1/4
        sections:
          sidebar:
            type: matomo-sidebar
            link: false
