title: Site

tabs:
  
  # Seo Tab
  seo:
    label: SEO
    icon: search
    columns:
      - width: 2/3
        sections:
          seoContent:
            type: fields
            fields:
              metaTitle:
                label: Meta Title
                type: text
                required: true
              metaDescription:
                label: Meta Description
                type: textarea
                buttons: false
                required: true

      - width: 1/3
        sections:
          seoImage:
            type: files
            headline: Social networks image
            min: 1
            max: 1
            required: true
            template: seo
            layout: cards
            info: "{{ file.dimensions }}"
            image:
              ratio: 3/2
              cover: true

          favicon:
            type: files
            headline: Favicon
            min: 1
            max: 1
            required: true
            template: favicon
            layout: cards
            info: "{{ file.dimensions }}"
            image:
              ratio: 1/1
              cover: true