title: Website

tabs:
  content:
    label: Content
    icon: folder
    sections:
      sectionA:
        type: pages
        headline: Menu pages
        info: "{{ page.subtitle }}"
        image: false
        templates:
          - essay
          - mapping
          - video
          - datavisualisation
      sectionB:
        type: pages
        headline: About
        image: false
        template: annex

  seo: tabs/seo